<?php
namespace Limbonia\Controller;

/**
 * Limbonia Profile Controller class
 *
 * Admin controller for handling the profile of the logged in user
 *
 * @author Lonnie Blansett <lonnie@limbonia.tech>
 * @package Limbonia
 */
class Profile extends \Limbonia\Controller
{
  use \Limbonia\Traits\ModelController;

  /**
   * The admin group that this controller belongs to
   *
   * @var string
   */
  protected static $sGroup = 'Hidden';

  /**
   * List of controllers this controller depends on to function correctly
   *
   * @var array
   */
  protected static $aControllerDependencies = ['user'];

  /**
   * The type of controller this is
   *
   * @var string
   */
  protected $sType = 'Profile';

  /**
   * Lists of columns to ignore when filling view data
   *
   * @var array
   */
  protected $aIgnore =
  [
    'edit' =>
    [
      'UserID',
      'Password',
      'Type',
      'Position',
      'Notes',
      'Active',
      'Visible'
    ],
    'create' => [],
    'search' =>
    [
      'Password',
      'ShippingAddress',
      'StreetAddress',
      'Notes'
    ],
    'view' =>
    [
      'Password',
      'Type',
      'Notes',
      'Active',
      'Visible'
    ],
    'boolean' =>
    [
      'Active',
      'Visible'
    ]
  ];

  /**
   * List of column names in the order required
   *
   * @var array
   */
  protected $aColumnOrder = ['FirstName', 'LastName'];

  /**
   * The default method for this controller
   *
   * @var string
   */
  protected $sDefaultAction = 'view';

  /**
   * The current method being used by this controller
   *
   * @var string
   */
  protected $sCurrentAction = 'view';

  /**
   * List of menu items that this controller should display
   *
   * @var array
   */
  protected $hMenuItems =
  [
    'view' => 'View',
    'edit' => 'Edit',
    'tickets' => 'Tickets',
    'changepassword' => 'Change Password'
  ];

  /**
   * List of sub-menu options
   *
   * @var array
   */
  protected $hSubMenuItems = [];

  /**
   * List of actions that are allowed to run
   *
   * @var array
   */
  protected $aAllowedActions = ['editdialog', 'edit', 'view', 'changepassword', 'tickets'];

  /**
   * List of valid HTTP methods
   *
   * @var array
   */
  protected static $hHttpMethods =
  [
    'head',
    'get',
    'put',
    'options'
  ];

  /**
   * Generate and set this controller's model, if there is one
   */
  protected function init()
  {
    $this->oModel = $this->oApp->user();
  }

  /**
   * Process the posted password changes
   *
   * @throws Exception
   */
  protected function prepareViewPostChangepassword()
  {
    $hData = $this->editGetData();

    if ($hData['Password'] != $hData['Password2'])
    {
      $this->oApp->viewData('failure', "The passwords did not match. Please try again.");
      $this->oApp->server['request_method'] = 'GET';
      return true;
    }

    try
    {
      $this->oApp->validatePassword($hData['Password']);
    }
    catch (\Exception $e)
    {
      $this->oApp->viewData('failure', $e->getMessage() . ' Please try again');
      $this->oApp->server['request_method'] = 'GET';
      return true;
    }

    $this->oModel->password = $hData['Password'];

    if ($this->oModel->save())
    {
      $this->oApp->viewData('success', "The password change has been successful.");
    }
    else
    {
      $this->oApp->viewData('failure', "The password change has failed.");
    }

    if (isset($_SESSION['EditData']))
    {
      unset($_SESSION['EditData']);
    }

    $this->oApp->server['request_method'] = 'GET';
    $this->sCurrentAction = 'view';
  }

  /**
   * Perform the base "GET" code then return null on success
   *
   * @return null
   * @throws \Exception
   */
  protected function processApiHead()
  {
    return null;
  }

  /**
   * Perform and return the default "GET" code
   *
   * @return array
   * @throws \Exception
   */
  protected function processApiGet()
  {
    return $this->processApiGetModel();
  }

  /**
   * Run the default "PUT" code and return the updated data
   *
   * @return array
   * @throws \Exception
   */
  protected function processApiPut()
  {
    if (!is_array($this->oRouter->data) || count($this->oRouter->data) == 0)
    {
      throw new \Exception('No valid data found to process', 400);
    }

    return $this->processApiPutModel();
  }

  /**
   * Echo the form generated by the specified data
   *
   * @param string $sType
   * @param array $hFields
   * @param array $hValues
   */
  public function getForm($sType, $hFields, $hValues = [])
  {
    return \Limbonia\Controller::getForm($sType, $hFields, $hValues);
  }
}